### ISSUE TITLE
Enhance Shape-DSL

### ISSUE THREAD

**Issue by markusheilig** [Zeta-Project/zeta#128]
Check for undefined concept elements in edges

**Comment by markusheilig** [comment]
done:
 - check1: check if referenced concept class exists
 - check2: check if reference concept reference exists
- check3: check if target concept class exists

todo:
- check the given connections are valid (validate connections against meta-model connections)

**Comment by sikell** [comment]
Relates to #127

**Comment by MarcelLuz** [comment]
Resolves #127
