### ISSUE TITLE
Bug inheritance for meta model entities

### ISSUE THREAD

**Issue by sikell** [Zeta-Project/zeta#160]
Meta model entities, which inherits an edge connection from their parent could configure this connection (edge) in shape but could not link in editor.
"These elements are not linkable!"

Unclear whether this is a frontend or backend bug.

**Comment by markusheilig** [comment]
![Screen Shot 2018-04-20 at 13.00.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a1016448d74e30012c03b54/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f36b7191a379ec0c2b51415d4bbe5d4a1f06a3a3dc78e2a436628f555ebfd53f5721c36917a9b1d11fbf00ee21824e80e2bd9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5cf449e34d5da5133666f43b.png)

-> "dropAnchor" connection
