### ISSUE TITLE
Conventions for Testing

### ISSUE THREAD

**Issue by MarcelLuz** [Zeta-Project/zeta#17]
- analyse wordspec (scala-testing-suite)
- use matcher instead of insert (refactor our tests)

**Comment by aullik** [comment]
Duplicate StyleParserImplTest For all Specs. 

- StyleParserImplTestFlatSpec
- StyleParserImplTestWordSpec
- StyleParserImplTestFreeSpec

on branch evaluate/testSuite/#17

**Comment by aullik** [comment]
![Example of FlatSpec test execution](https://user-images.githubusercontent.com/5610372/33308690-bd4c4866-d41b-11e7-96dc-bc5af5be973f.png)

**Comment by aullik** [comment]
Example of WordSpec test execution

![wordspec](https://user-images.githubusercontent.com/5610372/33309766-9c78f8a6-d41f-11e7-8f52-30d5ee75ab6b.PNG)

**Comment by aullik** [comment]
FreeSpec example that demonstrates that different test conventions can be used.

![freespec](https://user-images.githubusercontent.com/5610372/33359997-eea101de-d4d1-11e7-897a-7a8b6dea33fd.PNG)

**Comment by markusheilig** [comment]
team voted for freespec!
