### ISSUE TITLE
EdgeModel in UMLEdgeStyle einbinden

### ISSUE THREAD

**Issue by dkoch2** [Zeta-Project/zeta#225]
Wie UMLClassModel benötigt zeta eine Möglichkeit Edges und deren Attribute zu halten.

Wichtige Variablen:
UpperBounds
LowerBounds
Attribute
zu ergänzen

Außerdem müssen alle Zugriffe auf edge angepasst werden.
Bereits bekannt:
Graph.js - edge Labels

**Comment by dkoch2** [comment]
Die Klasse UMLEdgeStyleFactory hält folgende Daten:
    "references": [
    {
        "name": "toTransition",
        "description": "",
        "sourceDeletionDeletesTarget": false,
        "targetDeletionDeletesSource": false,
        "sourceClassName": "Place",
        "targetClassName": "Transition",
        "sourceLowerBounds": 0,
        "sourceUpperBounds": -1,
        "targetLowerBounds": 0,
        "targetUpperBounds": -1,
        "attributes": [],
        "methods": []
    },
Alternativ in definition.js nachlesen.

**Comment by dkoch2** [comment]
clickEvent: wie in NodeStyle hinzufügen
Model in EdgeStyle einbinden

**Comment by tobias-spott** [comment]
obsolet
