### ISSUE TITLE
Frontend: Coverage Tool 

### ISSUE THREAD

**Issue by pat-St** [Zeta-Project/zeta#447]
Marko suggested/prefers: https://coveralls.io/

**Comment by pat-St** [comment]
There may be some problems with the sbt plugin, because it is no longer maintained. [See repo](https://github.com/scoverage/sbt-coveralls)  Therefore we should keep Codecov for api.

**Comment by pat-St** [comment]
Implemented in [Branch](https://github.com/Zeta-Project/zeta/tree/coverage_tool)

**Comment by tobias-spott** [comment]
Mit Bezug auf Kommentar von Patrick am 27. Januar 2021 --> Implementiert - kann geschlossen werden
