### ISSUE TITLE
Mail: Forgot Password new Workflow

### ISSUE THREAD

**Issue by pat-St** [Zeta-Project/zeta#456]
## Old Workflow:
1. User click **forgot password** in Frontend 
2. Frontend triggers Backend 
3. Backend send mail to user with token and link for password  change
4. User open new Mail 
5. User follow the link to the Backend view and change password.
## New Workflow: 
1. User click **forgot password** in Frontend 
2. Frontend sends Backend generated token with link to itself 
3. Backend send mail to user with link from Frontend for password change
4. User open new Mail 
5. User follow the link to frontend and change password.

**Comment by Sebi1006** [comment]
Ticket ins Jira überführt --> [ZETA-36](https://kp2.in.htwg-konstanz.de/jira7/browse/ZETA-36)
