### ISSUE TITLE
Frontend: implement generic shape, style and diagram usage in model editor

### ISSUE THREAD

**Issue by pat-St** [Zeta-Project/zeta#461]
the editor changes the usage and behavior of the components  on the configuration from `/rest/v2/meta-models/:metaModelId/shape` and `/rest/v2/meta-models/:metaModelId/diagram`.
At first create hard coded objects for implementation.

**Comment by LukeCaruzo** [comment]
REST API -> modelid to metamodelid should be transformable.

**Comment by LukeCaruzo** [comment]
the concept editor changes the visual style of the components on the configuration from /rest/v2/meta-models/:metaModelId/style.
At first create hard coded objects for implementation.

**Comment by pat-St** [comment]
`/rest/v1/models/:modelId` now contains Meta Model data

**Comment by Sebi1006** [comment]
Ticket ins Jira überführt --> [ZETA-19](https://kp2.in.htwg-konstanz.de/jira7/browse/ZETA-19)
