### ISSUE TITLE
zetalayout/overview sidebar bug

### ISSUE THREAD

**Issue by wijon** [Zeta-Project/zeta#475]
Sometimes the sidebar in zetalayout/overview pops up and cannot be closed again:

![image](https://user-images.githubusercontent.com/44641733/108901511-3f1d2000-761b-11eb-8143-e4d86e0cc378.png)

Should only show on small displays.

**Comment by Sebi1006** [comment]
Ticket ins Jira überführt --> [ZETA-12](https://kp2.in.htwg-konstanz.de/jira7/browse/ZETA-12)
