### ISSUE TITLE
Only possible to change name 1 time for an attribute in concept editor

### ISSUE THREAD

**Issue by kolomu** [Zeta-Project/zeta#476]
![image](https://user-images.githubusercontent.com/12582455/109301983-ff338400-7838-11eb-9d27-7e2662725e3c.png)
When you click on an Attribute you have the ability to change the label one time. After that it is moved to the left and it's not possible to click there again

**Comment by tobias-spott** [comment]
Überführt ins JIRA --> [ZETA-18](https://kp2.in.htwg-konstanz.de/jira7/browse/ZETA-18)
