### ISSUE TITLE
Adding an Attribute in Class Diagram creates error 400

### ISSUE THREAD

**Issue by kolomu** [Zeta-Project/zeta#477]
When adding an attribute in the concept editor, the attribute is just added in the preview and not saved for the shape dsl.

The error is:

```{"obj[1][3]":[{"msg":["'globalUnique' is undefined on object: {\"name\":\"text414\"}"],"args":[]}]}```

![error-saving-attribute](https://user-images.githubusercontent.com/12582455/109396213-ce367a80-7930-11eb-86a1-cb950ffc0a9d.gif)

**Comment by Sebi1006** [comment]
Issue / Bug wurde im Jira angelegt / überführt --> ZETA-13
