### ISSUE TITLE
Remove VR-Editor

### ISSUE THREAD

**Issue by phaldan** [Zeta-Project/zeta#5]
The VR-Editor was an experiment and will no longer be used.

VR-Editor Files:
* /api/server/app/de/htwg/zeta/server/generator/generators/vr/
* /api/server/app/views/VrEditor.scala.html
* /api/server/app/assets/vr.png
* /api/server/public/components/bower_components

Used in:
* /api/server/conf/routes
* /api/server/app/controllers/ScalaRoutes.scala
* /api/server/app/de/htwg/zeta/server/controller/ModelController.scala
* /api/server/app/views/model/ModelGraphicalEditor.scala.html

**Comment by paleber** [comment]
done in 727ed8bbb6fb53753d6717c073e78116ddb77ff7
