### ISSUE TITLE
Create Style-Parser / Style-Model

### ISSUE THREAD

**Issue by markusheilig** [Zeta-Project/zeta#7]

**Comment by aullik** [comment]
Wir arbeiten auf dem Branch [task/style-parser](https://github.com/Zeta-Project/zeta/tree/task/style-parser)

**Comment by MarcelLuz** [comment]
Highlighting-Attribute müssen noch abgesprochen werden

**Comment by markusheilig** [comment]
implement cycle check for extension graphs
