### ISSUE TITLE
Connect JointJS with REST-API V1

### ISSUE THREAD

**Issue by jabodend** [Zeta-Project/zeta#83]
1.) Connect current state
2.) Connect new elements (new GeoModels)

**Comment by phaldan** [comment]
An overview of the generated javascript files and where they are used.

**/inspector.js (lodash)**
* InspectorDefs
  * webapp/src/graphical-editor/model.js

**/style.js**
* getStyle
  * /elementAndInlineStyle.js
  * /connectionstyle.js
* getDiagramHighlighting
  * /stencil.js

**/shape.js (joint)**
* joint.shapes.zeta
  * webapp/src/graphical-model-editor.js
  * webapp/src/graphical-editor/model.js
  * webapp/src/graphical-editor/model/ext/zeta.link.js

**/stencil.js (jquery, document-ready)**
* Stencil.groups
  * webapp/src/graphical-editor/model.js

**/connectionstyle.js (jquery)**
* getConnectionStyle
  * webapp/src/graphical-editor/model/ext/linkTypeSelector.js
  * webapp/src/graphical-editor/model/ext/contextMenu.js
* getPlacings
  * webapp/src/graphical-editor/model/ext/linkTypeSelector.js
  * webapp/src/graphical-editor/model/ext/contextMenu.js
* getLabels
  * webapp/src/graphical-editor/model/ext/linkTypeSelector.js
  * webapp/src/graphical-editor/model/ext/contextMenu.js

**/linkhelper.js**
* linkhelper
  * webapp/src/graphical-editor/model/ext/exportModel.js
  * webapp/src/graphical-editor/model/ext/contextMenu.js

**/validator.js**
* validator
  * webapp/src/graphical-editor/model/ext/linkTypeSelector.js
  * webapp/src/graphical-editor/model/ext/contextMenu.js

**/elementAndInlineStyle.js**
* getShapeStyle
  * /stencil.js

**Comment by MarcelLuz** [comment]
Notes:
Editor-Left-Side = Stancil
Editor-Right-Side = Inspector

JS-Files
(style.js, shape.js, ...) are loaded directly from database

**Comment by MarcelLuz** [comment]
ToDOs:
- connect OLD Files (static JS) to Editor
- dynamic impl for Style (for old API)
- dynamic impl for Diagram (for old API)
- dynamic impl for Shape (for old API)

**Comment by phaldan** [comment]
Mapping content of output files from Scala Generator to new native JavaScript implementation:

| Scala Generator|JavaScript (webapp/src/graphical-editor/model/generator)|
|-----------|---------------|
|_/inspector.js_ => InspectorDefs| [shape/InspectorGenerator.js => InspectorDefs](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/shape/InspectorGenerator.js#L354) |
|_/style.js_ => getStyle| [StyleGenerator.js => getStyle](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/StyleGenerator.js#L185) |
|_/style.js_ => getDiagramHighlighting| [StyleGenerator.js => getDiagramHighlighting](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/StyleGenerator.js#L190) |
|_/shape.js_ => joint.shapes.zeta| [shape/ShapeDefinitionGenerator.js => zeta](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/shape/ShapeDefinitionGenerator.js#L349) |
|_/stencil.js_ => Stencil.groups| [diagram/StencilGenerator.js => groups](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/StencilGenerator.js#L118) |
|_/stencil.js_ => Stencil.shapes| [diagram/StencilGenerator.js => shapes](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/StencilGenerator.js#L126) |
|_/connectionstyle.js_ => getConnectionStyle| [ConnectionDefinitionGenerator.js => getConnectionStyle](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/ConnectionDefinitionGenerator.js#L95) |
|_/connectionstyle.js_ => getPlacings| [ConnectionDefinitionGenerator.js => getPlacings](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/ConnectionDefinitionGenerator.js#L100) |
|_/connectionstyle.js_ => getLabels| [ConnectionDefinitionGenerator.js => getLabels](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/ConnectionDefinitionGenerator.js#L105) |
|_/linkhelper.js_ => linkhelper.getLabelText| [diagram/LinkHelperGenerator.js => getLabelText](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/LinkHelperGenerator.js#L47) |
|_/linkhelper.js_ => linkhelper.mapping| [diagram/LinkHelperGenerator.js => mapping](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/LinkHelperGenerator.js#L52) |
|_/validator.js_ => validator.inputMatrix| [diagram/ValidatorGenerator.js => inputMatrix](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/ValidatorGenerator.js#L51) |
|_/validator.js_ => validator.outputMatrix| [diagram/ValidatorGenerator.js => outputMatrix](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/ValidatorGenerator.js#L58) |
|_/validator.js_ => validator.getEdgeData| [diagram/ValidatorGenerator.js => getEdgeData](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/ValidatorGenerator.js#L65) |
|_/validator.js_ => validator.getValidEdges| [diagram/ValidatorGenerator.js => getValidEdges](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/diagram/ValidatorGenerator.js#L77) |
|_/elementAndInlineStyle.js_ => getShapeStyle| [shape/StyleGenerator.js => getShapeStyle](../blob/cdbb1c817efea89168f0be9cfe80495466a2bbd6/webapp/src/graphical-editor/model/generator/shape/StyleGenerator.js#L84) |

**Comment by MarcelLuz** [comment]
Logic for the red frame (validator) is still buggy

**Comment by MarcelLuz** [comment]
Inspector does not display all elements for a shape.

**Comment by MarcelLuz** [comment]
- validator has no boundings
- inspector  still has dependencies to uuid in static JSON or code
